### ISSUE TITLE
请问那个build 是干什么用的 

### ISSUE THREAD

**Issue by zongxiaomi** [TOP-Chao/lottery#2]
js小白最纯真的请教，我用了Hbuild 里面的link 只有引用build下面的js文件才有用，引用src的就不管用，不知道为什么

**Comment by zongxiaomi** [comment]
不好意思说错了，比如实在dial.html中，''<script src="./dist/dial.js"></script>'' 能运行，而引用<script src="./src/dial.js"></script> 却不行

**Comment by 94cstyles** [comment]
src目录的是源文件 用es6写的~ 是可以用的 是你使用姿势不对~ 如果你不了解es6 请先看这篇文章[ECMAScript 6 入门](http://es6.ruanyifeng.com/)  
dist目录是es6打包编译好的 生成es5语法的文件~ 如果想了解es6 -> es5 请先了解[babel](https://babeljs.io/) ~ 如果想了解打包 可以看 [rollup](https://rollupjs.org/) 或者 [webpack](https://webpack.js.org/) 或者 [gulp](http://gulpjs.com/)

**Comment by zongxiaomi** [comment]
@TOP-Chao 哈哈哈 ，谢谢 说的很详细，已经做了两个月的React-native，现在都是用的Es6 去编写，我不明白的是 为什么要把Es6-> Es5呢？ 还有为什么要打包呢，js不是即时编译的动态脚本型语言吗？ 我先猜一下，是不是现在浏览器还不能运行Es6语法的js。打包是为了压缩代码大小。我会去看你说的那些东西，自己动手丰衣足食。

**Comment by 94cstyles** [comment]
谷歌浏览器对es6支持还算可以 其他浏览器以及手机就差远了~ 打包除了压缩还可以做很多操作，es6 -> es5这个过程也是打包~ 其实你去了解 webpack后 会知道的。
