### ISSUE TITLE
移动端图片不能平铺

### ISSUE THREAD

**Issue by juxiu** [TOP-Chao/lottery#4]
设置图片之后，图片宽高比canvas宽高大

**Comment by 94cstyles** [comment]
你是说的那个 刮刮卡 `setResult ` ? 这个是设置背景，你使用 `background-size`，`background-repeat` 控制

**Comment by juxiu** [comment]
感谢作者回复，不是setResult，是刮刮卡的涂层，new Img之后传进去，图片不能百分百填充canvas画布，图片比画布要大许多，只显示图片的一部分。

**Comment by juxiu** [comment]
还有个问题，当文档高度超出可视区域，文档向上滑动之后，绘制起点的位置有偏差

**Comment by 94cstyles** [comment]
推荐你fork一份，在[这里](https://github.com/94cstyles/lottery/blob/master/src/card.js#L54)对代码进行修改。需要你添加新的参数，修改drawImage。
或者你不想修改源码，你可以创建一个canvas对图像进行调整大小然后转换为base64，再创建Image传递过来。

**Comment by juxiu** [comment]
感谢，改了源码
